name: BuffBattleRoyale
version: '${project.version}'
main: com.kumo0621.github.buffbattleroyale.BuffBattleRoyale
api-version: '1.21'
commands:
  buffitem:
    description: バフアイテムを取得するコマンド
    usage: /buffitem
    permission: buffbattleroyale.use
  buffstatus:
    description: 現在装備しているバフ効果を表示するコマンド
    usage: /buffstatus
    permission: buffbattleroyale.use

permissions:
  buffbattleroyale.use:
    description: BuffBattleRoyale のコマンドを使用できる権限 (OP のみ)
    default: op